# Workflow to build and deploy MERN stack app to Azure Web Apps
name: Build and Deploy MERN Stack to Azure

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Zip Backend Artifact
        working-directory: ./backend
        run: zip -r backend.zip ./*

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ./backend/backend.zip

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies and Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Zip Frontend Artifact
        working-directory: ./frontend
        run: zip -r frontend.zip ./build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: ./frontend/frontend.zip

  deploy-backend:
    name: Deploy Backend to Azure
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip Backend Artifact
        run: unzip backend.zip -d ./backend

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bridge-point-backend' # Replace with your backend App Service name
          slot-name: 'production'
          package: ./backend
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}

  deploy-frontend:
    name: Deploy Frontend to Azure
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact

      - name: Unzip Frontend Artifact
        run: unzip frontend.zip -d ./frontend

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bridge-point-frontend' # Replace with your frontend App Service name
          slot-name: 'production'
          package: ./frontend/build
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
